// <auto-generated />
namespace _2_FirstAppQuotesAPIWithDBEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class QuoteValidationAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuoteValidationAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202502031241165_QuoteValidationAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
